services:
  drivewaycam:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: LodgiaCam
    environment:
    - PGID=${PGID}
    - PUID=${PUID}
    - TZ=${TZ}
    - CAMERA_NAME=lodgia
    hostname: ${HOSTNAME}
    logging:
      driver: json-file
      options:
        max-file: ${LOGGING_MAXFILE}
        max-size: ${LOGGING_MAXSIZE}
    restart: unless-stopped
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - ${TIMELAPS_DIR}/:/timelapse_data
