services:
  lodgiacam: #If multiple cams, this needs to be unique for each service
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${CAMERA_NAME}Cam
    environment:
    - PGID=${PGID}
    - PUID=${PUID}
    - TZ=${TZ}
    - CAMERA_NAME=${CAMERA_NAME}
    - IMAGE_CRON_PATTERN=${IMAGE_CRON_PATTERN}
    - MOVIE_CRON_PATTERN=${MOVIE_CRON_PATTERN}
    - #CAMERA_RTSP="rtsp://user:password@IP:554/stream"
    - CAMERA_RTSP=${CAMERA_RTSP}
    - #OVERLAY_TXT_FILE="overlay.txt"
    - OVERLAY_TXT_FILE=${OVERLAY_TXT_FILE}
    - OVERLAY_FONT_FILE=${OVERLAY_FONT_FILE}
    - DAYS_TO_KEEP=${DAYS_TO_KEEP}
    hostname: ${HOSTNAME}
    logging:
      driver: json-file
      options:
        max-file: ${LOGGING_MAXFILE}
        max-size: ${LOGGING_MAXSIZE}
    restart: unless-stopped
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - ${TIMELAPS_DIR}/:/timelapse_data
